In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

In [58]:
df = pd.read_csv("data/proj3/international_matches.csv")
df.head()

,date,home_team,away_team,home_team_continent,away_team_continent,home_team_fifa_rank,away_team_fifa_rank,home_team_total_fifa_points,away_team_total_fifa_points,home_team_score,...,shoot_out,home_team_result,home_team_goalkeeper_score,away_team_goalkeeper_score,home_team_mean_defense_score,home_team_mean_offense_score,home_team_mean_midfield_score,away_team_mean_defense_score,away_team_mean_offense_score,away_team_mean_midfield_score
0,1993-08-08,Bolivia,Uruguay,South America,South America,59,22,0,0,3,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1993-08-08,Brazil,Mexico,South America,North America,8,14,0,0,1,...,No,Draw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1993-08-08,Ecuador,Venezuela,South America,South America,35,94,0,0,5,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1993-08-08,Guinea,Sierra Leone,Africa,Africa,65,86,0,0,1,...,No,Win,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1993-08-08,Paraguay,Argentina,South America,South America,67,5,0,0,1,...,No,Lose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,23911,23912,23913,23914,23915,23916,23917,23918,23919,23920
date,1993-08-08,1993-08-08,1993-08-08,1993-08-08,1993-08-08,1993-08-08,1993-08-08,1993-08-09,1993-08-11,1993-08-11,...,2022-06-14,2022-06-14,2022-06-14,2022-06-14,2022-06-14,2022-06-14,2022-06-14,2022-06-14,2022-06-14,2022-06-14
home_team,Bolivia,Brazil,Ecuador,Guinea,Paraguay,Peru,Zimbabwe,Guinea,Faroe Islands,Sweden,...,Ukraine,Bosnia and Herzegovina,Romania,Luxembourg,Turkey,Moldova,Liechtenstein,Chile,Japan,Korea Republic
away_team,Uruguay,Mexico,Venezuela,Sierra Leone,Argentina,Colombia,Eswatini,Sierra Leone,Norway,Switzerland,...,Republic of Ireland,Finland,Montenegro,Faroe Islands,Lithuania,Andorra,Latvia,Ghana,Tunisia,Egypt
home_team_continent,South America,South America,South America,Africa,South America,South America,Africa,Africa,Europe,Europe,...,Europe,Europe,Europe,Europe,Europe,Europe,Europe,South America,Asia,Asia
away_team_continent,South America,North America,South America,Africa,South America,South America,Africa,Africa,Europe,Europe,...,Europe,Europe,Europe,Europe,Europe,Europe,Europe,Africa,Africa,Africa
home_team_fifa_rank,59,8,35,65,67,70,50,65,111,4,...,27,59,48,94,43,180,192,28,23,29
away_team_fifa_rank,22,14,94,86,5,19,102,86,9,3,...,47,57,70,124,138,153,135,60,35,32
home_team_total_fifa_points,0,0,0,0,0,0,0,0,0,0,...,1535,1388,1446,1229,1461,932,895,1526,1553,1519
away_team_total_fifa_points,0,0,0,0,0,0,0,0,0,0,...,1449,1406,1342,1137,1092,1040,1105,1387,1499,1500
home_team_score,3,1,5,1,1,0,2,4,0,1,...,1,3,0,2,2,2,0,0,0,4
away_team_score,1,1,0,0,3,1,0,0,7,2,...,1,2,3,2,0,1,2,0,3,1
tournament,FIFA World Cup qualification,Friendly,FIFA World Cup qualification,Friendly,FIFA World Cup qualification,FIFA World Cup qualification,Friendly,Friendly,Friendly,Friendly,...,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,Kirin Cup,Kirin Cup,Friendly
city,La Paz,Maceió,Quito,Conakry,Asunción,Lima,Harare,Conakry,Toftir,Borås,...,Łódź,Zenica,Bucharest,Luxembourg,İzmir,Chișinău,Vaduz,Suita,Suita,Seoul
country,Bolivia,Brazil,Ecuador,Guinea,Paraguay,Peru,Zimbabwe,Guinea,Faroe Islands,Sweden,...,Poland,Bosnia and Herzegovina,Romania,Luxembourg,Turkey,Moldova,Liechtenstein,Japan,Japan,Korea Republic
neutral_location,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
shoot_out,No,No,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Yes,No,No
home_team_result,Win,Draw,Win,Win,Lose,Lose,Win,Win,Lose,Lose,...,Draw,Win,Lose,Draw,Win,Win,Lose,Lose,Lose,Win
home_team_goalkeeper_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.0,76.0,77.0,69.0,79.0,65.0,NaN,79.0,73.0,75.0
away_team_goalkeeper_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.0,83.0,65.0,NaN,71.0,NaN,65.0,74.0,NaN,NaN
home_team_mean_defense_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.8,74.2,73.5,68.5,78.2,NaN,NaN,75.5,75.2,73.0
home_team_mean_offense_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78.7,77.0,73.7,NaN,76.7,NaN,NaN,76.7,75.0,80.0
home_team_mean_midfield_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.0,78.0,75.0,69.8,78.2,NaN,NaN,78.2,77.5,73.8
away_team_mean_defense_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76.5,70.0,76.2,NaN,NaN,NaN,NaN,75.5,70.8,NaN
away_team_mean_offense_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72.7,72.3,74.7,NaN,NaN,NaN,NaN,76.0,72.3,79.3
away_team_mean_midfield_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73.8,73.5,68.2,NaN,NaN,NaN,NaN,78.2,74.0,70.8

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23921 entries, 0 to 23920
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           23921 non-null  object
 1   home_team                      23921 non-null  object
 2   away_team                      23921 non-null  object
 3   home_team_continent            23921 non-null  object
 4   away_team_continent            23921 non-null  object
 5   home_team_fifa_rank            23921 non-null  int64
 6   away_team_fifa_rank            23921 non-null  int64
 7   home_team_total_fifa_points    23921 non-null  int64
 8   away_team_total_fifa_points    23921 non-null  int64
 9   home_team_score                23921 non-null  int64
 10  away_team_score                23921 non-null  int64
 11  tournament                     23921 non-null  object
 12  city                           23921 non-null  object
 13  country                        23921 non-null  object
 14  neutral_location               23921 non-null  bool
 15  shoot_out                      23921 non-null  object
 16  home_team_result               23921 non-null  object
 17  home_team_goalkeeper_score     8379 non-null   float64
 18  away_team_goalkeeper_score     8095 non-null   float64
 19  home_team_mean_defense_score   7787 non-null   float64
 20  home_team_mean_offense_score   8510 non-null   float64
 21  home_team_mean_midfield_score  8162 non-null   float64
 22  away_team_mean_defense_score   7564 non-null   float64
 23  away_team_mean_offense_score   8312 non-null   float64
 24  away_team_mean_midfield_score  7979 non-null   float64
dtypes: bool(1), float64(8), int64(6), object(10)
memory usage: 4.4+ MB

In [61]:
df_tmp = df.copy()

In [62]:
df_tmp["day"] = pd.to_datetime(df_tmp["date"]).dt.day
df_tmp["month"] = pd.to_datetime(df_tmp["date"]).dt.month
df_tmp["year"] = pd.to_datetime(df_tmp["date"]).dt.year

In [63]:
df_tmp.drop(["home_team_goalkeeper_score", "away_team_goalkeeper_score", "home_team_mean_defense_score", "home_team_mean_offense_score", "home_team_mean_midfield_score", "away_team_mean_defense_score", "away_team_mean_offense_score", "away_team_mean_midfield_score", "date"], inplace=True, axis=1)

In [64]:
df_tmp.T

,0,1,2,3,4,5,6,7,8,9,...,23911,23912,23913,23914,23915,23916,23917,23918,23919,23920
home_team,Bolivia,Brazil,Ecuador,Guinea,Paraguay,Peru,Zimbabwe,Guinea,Faroe Islands,Sweden,...,Ukraine,Bosnia and Herzegovina,Romania,Luxembourg,Turkey,Moldova,Liechtenstein,Chile,Japan,Korea Republic
away_team,Uruguay,Mexico,Venezuela,Sierra Leone,Argentina,Colombia,Eswatini,Sierra Leone,Norway,Switzerland,...,Republic of Ireland,Finland,Montenegro,Faroe Islands,Lithuania,Andorra,Latvia,Ghana,Tunisia,Egypt
home_team_continent,South America,South America,South America,Africa,South America,South America,Africa,Africa,Europe,Europe,...,Europe,Europe,Europe,Europe,Europe,Europe,Europe,South America,Asia,Asia
away_team_continent,South America,North America,South America,Africa,South America,South America,Africa,Africa,Europe,Europe,...,Europe,Europe,Europe,Europe,Europe,Europe,Europe,Africa,Africa,Africa
home_team_fifa_rank,59,8,35,65,67,70,50,65,111,4,...,27,59,48,94,43,180,192,28,23,29
away_team_fifa_rank,22,14,94,86,5,19,102,86,9,3,...,47,57,70,124,138,153,135,60,35,32
home_team_total_fifa_points,0,0,0,0,0,0,0,0,0,0,...,1535,1388,1446,1229,1461,932,895,1526,1553,1519
away_team_total_fifa_points,0,0,0,0,0,0,0,0,0,0,...,1449,1406,1342,1137,1092,1040,1105,1387,1499,1500
home_team_score,3,1,5,1,1,0,2,4,0,1,...,1,3,0,2,2,2,0,0,0,4
away_team_score,1,1,0,0,3,1,0,0,7,2,...,1,2,3,2,0,1,2,0,3,1
tournament,FIFA World Cup qualification,Friendly,FIFA World Cup qualification,Friendly,FIFA World Cup qualification,FIFA World Cup qualification,Friendly,Friendly,Friendly,Friendly,...,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,Kirin Cup,Kirin Cup,Friendly
city,La Paz,Maceió,Quito,Conakry,Asunción,Lima,Harare,Conakry,Toftir,Borås,...,Łódź,Zenica,Bucharest,Luxembourg,İzmir,Chișinău,Vaduz,Suita,Suita,Seoul
country,Bolivia,Brazil,Ecuador,Guinea,Paraguay,Peru,Zimbabwe,Guinea,Faroe Islands,Sweden,...,Poland,Bosnia and Herzegovina,Romania,Luxembourg,Turkey,Moldova,Liechtenstein,Japan,Japan,Korea Republic
neutral_location,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
shoot_out,No,No,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Yes,No,No
home_team_result,Win,Draw,Win,Win,Lose,Lose,Win,Win,Lose,Lose,...,Draw,Win,Lose,Draw,Win,Win,Lose,Lose,Lose,Win
day,8,8,8,8,8,8,8,9,11,11,...,14,14,14,14,14,14,14,14,14,14
month,8,8,8,8,8,8,8,8,8,8,...,6,6,6,6,6,6,6,6,6,6
year,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,...,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022

In [65]:
for stuff in df_tmp.keys():
    if pd.api.types.is_object_dtype(df_tmp[stuff]) == True:
        new_cat = pd.Categorical(df_tmp[stuff])
        df_tmp[stuff + "_cat"] = new_cat.codes

In [66]:
df_tmp.keys()

Index(['home_team', 'away_team', 'home_team_continent', 'away_team_continent',
       'home_team_fifa_rank', 'away_team_fifa_rank',
       'home_team_total_fifa_points', 'away_team_total_fifa_points',
       'home_team_score', 'away_team_score', 'tournament', 'city', 'country',
       'neutral_location', 'shoot_out', 'home_team_result', 'day', 'month',
       'year', 'home_team_cat', 'away_team_cat', 'home_team_continent_cat',
       'away_team_continent_cat', 'tournament_cat', 'city_cat', 'country_cat',
       'shoot_out_cat', 'home_team_result_cat'],
      dtype='object')

In [67]:
df_tmp["neutral_location_cat"] = pd.Categorical(df["neutral_location"]).codes

In [68]:
df_tmp.T

,0,1,2,3,4,5,6,7,8,9,...,23911,23912,23913,23914,23915,23916,23917,23918,23919,23920
home_team,Bolivia,Brazil,Ecuador,Guinea,Paraguay,Peru,Zimbabwe,Guinea,Faroe Islands,Sweden,...,Ukraine,Bosnia and Herzegovina,Romania,Luxembourg,Turkey,Moldova,Liechtenstein,Chile,Japan,Korea Republic
away_team,Uruguay,Mexico,Venezuela,Sierra Leone,Argentina,Colombia,Eswatini,Sierra Leone,Norway,Switzerland,...,Republic of Ireland,Finland,Montenegro,Faroe Islands,Lithuania,Andorra,Latvia,Ghana,Tunisia,Egypt
home_team_continent,South America,South America,South America,Africa,South America,South America,Africa,Africa,Europe,Europe,...,Europe,Europe,Europe,Europe,Europe,Europe,Europe,South America,Asia,Asia
away_team_continent,South America,North America,South America,Africa,South America,South America,Africa,Africa,Europe,Europe,...,Europe,Europe,Europe,Europe,Europe,Europe,Europe,Africa,Africa,Africa
home_team_fifa_rank,59,8,35,65,67,70,50,65,111,4,...,27,59,48,94,43,180,192,28,23,29
away_team_fifa_rank,22,14,94,86,5,19,102,86,9,3,...,47,57,70,124,138,153,135,60,35,32
home_team_total_fifa_points,0,0,0,0,0,0,0,0,0,0,...,1535,1388,1446,1229,1461,932,895,1526,1553,1519
away_team_total_fifa_points,0,0,0,0,0,0,0,0,0,0,...,1449,1406,1342,1137,1092,1040,1105,1387,1499,1500
home_team_score,3,1,5,1,1,0,2,4,0,1,...,1,3,0,2,2,2,0,0,0,4
away_team_score,1,1,0,0,3,1,0,0,7,2,...,1,2,3,2,0,1,2,0,3,1
tournament,FIFA World Cup qualification,Friendly,FIFA World Cup qualification,Friendly,FIFA World Cup qualification,FIFA World Cup qualification,Friendly,Friendly,Friendly,Friendly,...,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,UEFA Nations League,Kirin Cup,Kirin Cup,Friendly
city,La Paz,Maceió,Quito,Conakry,Asunción,Lima,Harare,Conakry,Toftir,Borås,...,Łódź,Zenica,Bucharest,Luxembourg,İzmir,Chișinău,Vaduz,Suita,Suita,Seoul
country,Bolivia,Brazil,Ecuador,Guinea,Paraguay,Peru,Zimbabwe,Guinea,Faroe Islands,Sweden,...,Poland,Bosnia and Herzegovina,Romania,Luxembourg,Turkey,Moldova,Liechtenstein,Japan,Japan,Korea Republic
neutral_location,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
shoot_out,No,No,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Yes,No,No
home_team_result,Win,Draw,Win,Win,Lose,Lose,Win,Win,Lose,Lose,...,Draw,Win,Lose,Draw,Win,Win,Lose,Lose,Lose,Win
day,8,8,8,8,8,8,8,9,11,11,...,14,14,14,14,14,14,14,14,14,14
month,8,8,8,8,8,8,8,8,8,8,...,6,6,6,6,6,6,6,6,6,6
year,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,...,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022
home_team_cat,24,27,59,82,148,149,210,82,68,181,...,200,25,156,114,194,125,112,40,97,102
away_team_cat,202,124,205,166,8,43,66,166,142,182,...,155,70,127,68,113,4,107,76,193,60
home_team_continent_cat,5,5,5,0,5,5,0,0,2,2,...,2,2,2,2,2,2,2,5,1,1
away_team_continent_cat,5,3,5,0,5,5,0,0,2,2,...,2,2,2,2,2,2,2,0,0,0
tournament_cat,37,38,37,38,37,37,38,38,38,38,...,74,74,74,74,74,74,74,46,46,38
city_cat,717,801,1141,341,93,759,537,341,1402,213,...,1571,1546,236,793,1569,309,1447,1337,1337,1278
country_cat,23,26,59,84,153,154,216,84,68,188,...,156,24,161,116,200,128,114,99,99,104
shoot_out_cat,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
home_team_result_cat,2,0,2,2,1,1,2,2,1,1,...,0,2,1,0,2,2,1,1,1,2
neutral_location_cat,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0

In [69]:
from sklearn.model_selection import train_test_split

X = df_tmp.drop(["home_team", "away_team", "home_team_continent", "away_team_continent", "city", "country", "shoot_out", "home_team_result", "home_team_result_cat", "tournament", "neutral_location"], axis=1)
y = df_tmp["home_team_result_cat"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [70]:
len(X_train), len(y_train), len(X_test), len(y_test)

(19136, 19136, 4785, 4785)

In [71]:
model_rr = RandomForestRegressor()
model_rr.fit(X_train, y_train)

RandomForestRegressor()

In [72]:
model_rr.score(X_test, y_test)

0.9936333339549566